### ISSUE TITLE
Extend pipeline reference with matrix feature

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#189]
For example, this would create `n` concurrent jobs with the same commands but different env vars.
```yaml
      jobs:
        - name: matrix job
          commands:
            - echo $ELIXIR
            - echo $ERLANG
          matrix:
            - env_var: ELIXIR
              values: ["1.3", "1.4"]
            - env_var: ERLANG
              values: ["19", "20", "21"]
```

There will be 6 jobs created because there are 6 elements in Cartesian product of env vars in matrix property:

- `ELIXIR=1.3` and `ERLANG=19`
- `ELIXIR=1.3` and `ERLANG=20`
- `ELIXIR=1.3` and `ERLANG=21`
- `ELIXIR=1.4` and `ERLANG=19`
- `ELIXIR=1.4` and `ERLANG=20`
- `ELIXIR=1.4` and `ERLANG=21`
