### ISSUE TITLE
Long one line command can be divided into more lines with '>-'

### ISSUE THREAD

**Issue by mimimalizam** [semaphoreci/docs#319]
One user recently [asked](https://github.com/renderedtext/issues/issues/1588) for a way to divide a long one line command and it can be achieved by writing the line in the folded style (`>`) and by stripping the line break in the yaml file (`-`). To do this, we can start the command with line containing only `>-` and write the command in more lines below it.

Example yaml:

```
version: "v1.0"
name: First pipeline example
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: "First block"
    task:
      jobs:
      - name: Divide one line command
        commands:
          - >- 
            sudo apt-get install -y
            htop
            git
            curl
            wget
```
