### ISSUE TITLE
Global Job Config

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#447]
We have an undocument very useful feature in our YAMLs — `global_job_config`.

Example of global_job_config that will apply the configuration to all jobs in a pipeline:

```
global_job_config:
  secrets:
    - name: raisins
  env_vars:
    - name: MEANING_OF_LIFE
       value: "42"
```

**Comment by DamjanBecirovic** [comment]
The `global_job_config` field is defined on the pipeline level, same as `blocks` or `promotions`, and it can contain any of these fields:
- `prologue`
- `epilogue`
- `secrets`
- `env_vars`

The defined configs have completely the same syntax as the ones defined on task level and are applied to all tasks and jobs in a pipeline.

In the case of  `prologue` and `env_vars` the global configs, ones from  `global_job_config`, are exported first, and after them, the ones defined on the task level. This allows overriding global configs for the specific task if there is a need for that.

In the case of `epilogue`, the order of exporting is reversed, so, for example, one can firstly perform specific cleanup commands before global ones.

The `secrets` are just merged together since ordering plays no role there.

Here is an example:

``` yml
version: "v1.0"
name: First Semaphore pipeline definition
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
global_job_config:
  prologue:
    commands:
      - checkout
  env_vars:
    - name: TEST_ENV_VAR
      value: test_value
blocks:
  - task:
      jobs:
        - name: job1
          commands:
            - echo $TEST_ENV_VAR
```
